### ISSUE TITLE
Gate guard doesn't close castle gate in chapter 4 

### ISSUE THREAD

**Issue by i5sue5** [AmProsius/gothic-1-community-patch#124] opened 2021-02-14 09:44 UTC
**Describe the bug**
Grd_280_Gardist has ID 230 instead of 280. Therefore he uses the routines of another NPC and the inner gate of the OC stays open in chapter IV.

**Expected behavior**
Gate guard of the castle now has the correct routine and stands at the gate.

**Comment by AmProsius** [comment] 2021-02-16 19:04
*Possibly*

https://github.com/AmProsius/gothic-1-community-patch/blob/2775fbc70322594ed1d00c96717143f0c2af5af7/scriptbase/_work/Data/Scripts/Content/Story/NPC/GRD_280_Gardist.d#L5-L11

changed to

```d
    name        =   NAME_Gardist;
    npctype     =   npctype_guard;
    flags       =   NPC_FLAG_IMMORTAL;  // weil Windenwache !!! wird in Kapitel 4 gelöscht!
    guild       =   GIL_GRD;
    level       =   20;
    voice       =   6;
    id          =   280;
```

**Comment by szapp** [comment] 2021-02-16 20:47
This fix might be a bit tricky, because it both relies on a game-save fix (if the NPC is already in the world) and a session-fix (if the NPC is yet to be spawned). Splitting a fix like this is currently not easily supported by our current script setup. I will have a look how to implement it.

**Comment by szapp** [comment] 2021-02-17 11:39
Scratch that. It would in fact be an issue if the NPC was created during a running game. This particular NPC is only created once at new game. As game-save fixes are applied after the new game started, they will suffice. No session-fix necessary here.

**Comment by szapp** [comment] 2021-02-21 14:19
> Gate guard now correctly closes the inner gate of the Old Camp in chapter 4.

Just out of curiosity: Which one is the inner gate? Is that the castle gate?

**Comment by AmProsius** [comment] 2021-02-21 16:52
> Which one is the inner gate? Is that the castle gate?

If I'm not mistaken the inner gate is the castle gate, right.

**Comment by szapp** [comment] 2021-02-27 16:02
I noticed that changing the NPC's ID does in fact correct the daily routine (the NPC now stands beside the gate wheel). Nevertheless, the gate is not closing, even when manually turning the wheel. It looks to me that the wheel is not triggering the gate.

**Comment by szapp** [comment] 2021-02-27 16:23
Here are screenshots for the gate (first image) and the switch (second image) from the spacer. Within the spacer, triggering the switch closes the gate. So, the problem must be somewhere else. I am aware that switches break during saving and loading, but in a fresh new game the main gate of the Old Camp can be closed and opened while the castle gate remains stuck.

![gate](https://user-images.githubusercontent.com/20203034/109393105-3e88d000-7920-11eb-8664-d5da9e7d42d7.png) ![wheel](https://user-images.githubusercontent.com/20203034/109393107-40529380-7920-11eb-92c8-6f0dac937701.png)

**Comment by szapp** [comment] 2021-02-27 18:39
Here the properties of the main gate of the Old camp and the corresponding switch (for comparison).

![maingate](https://user-images.githubusercontent.com/20203034/109396796-8402c880-7933-11eb-86c6-38714a90363c.png) ![maingateswitch](https://user-images.githubusercontent.com/20203034/109396799-87964f80-7933-11eb-8261-50d052173c67.png)

**Comment by szapp** [comment] 2021-02-27 20:03
I will continue about the gate in a separate issue.

**Comment by szapp** [comment] 2022-02-05 20:59
This fix can be implemented much easier and as a session fix. The property `C_Npc.id` is not loaded from the gamesave as previously assumed. Half the implemented fix suffices (and can be simplified).

**Comment by szapp** [comment] 2022-02-06 11:05
@AmProsius can you pull branch `bug124` run the test and confirm? Then we can merge it and delete it again.

**Comment by AmProsius** [comment] 2022-02-06 19:18
Confirmed. I will close this issue then.

**Closed by AmProsius** 2022-02-06 19:18 UTC
Labels: provided fix, change npc instance variable (int), deviates from template
