### ISSUE TITLE
The Ice Golem protecting Xardas' Tower has two hearts in his inventory

### ISSUE THREAD

**Issue by Ilvatar** [AmProsius/gothic-1-community-patch#250] opened 2021-12-07 09:18 UTC
**Describe the bug**
The Ice Golem protecting Xardas' Tower has two hearts in his inventory instead of one.

**Expected behavior**
The Ice Golem only has one heart in his inventory.

**Steps to reproduce the issue**
1. Defeat the Ice Golem
2. Search his inventory
3. There are two hearts instead of one

**Additional context**
![Screenshot (2)](https://user-images.githubusercontent.com/95682241/145001169-80213c61-18d8-4eea-af10-f2914d9e3b42.png)

**Comment by szapp** [comment] 2021-12-07 11:10
Looking at the scripts, I would not call this a bug, but rather intended behavior. Note, that the golem does not have **two hearts**. The two items are not identical. One is the heart, a quest item, and one is a "piece of the ice golem". Although I cannot follow what the purpose of this might have been, I would not call this a bug and would advise against changing this, in case a mod reinstates a possible original intention/quest around it.

### Additional information
https://github.com/AmProsius/gothic-1-community-patch/blob/b946ba1189a6937510bfbfaeff64a2df55d9cccb/scriptbase/_work/Data/Scripts/Content/AI/Monster/MST_Golem.d#L166-L193

https://github.com/AmProsius/gothic-1-community-patch/blob/b946ba1189a6937510bfbfaeff64a2df55d9cccb/scriptbase/_work/Data/Scripts/Content/Items/AnimalTrophy.d#L420-L462

**Comment by Ilvatar** [comment] 2021-12-07 11:35
You are totally right. I never realized those were two different items.
I thought it just was odd that there was no equivalent for the Fire Golem.

**Comment by szapp** [comment] 2021-12-07 13:16
I agree. It is odd and I don't understand. Only after I looked into the scripts, it appears to be intended - in some sort of way. If you don't mind, I will close this issue. We can re-open it, should there be any follow up thoughts on it.

**Closed by szapp** 2021-12-07 13:16 UTC
Labels: validation: required, opinionated
