### ISSUE TITLE
Can't take swampweed from Balor twice if first time I already asked him about a New Camp trader

### ISSUE THREAD

**Issue by MarkusRamikin** [AmProsius/gothic-1-community-patch#320] opened 2022-02-06 01:13 UTC
Normally, after Baal Orun tells me to collect the weed harvest, I can take 50 swampweed from Viran and 50 from Balor. After taking it to Cor Kalom and progressing the date, I can get another 50 from Balor and another from Viran.

If I question Balor about someone to sell the weed to, but only during the second harvest, everything is fine, I still get 50 weed from him (and 50 from Viran).

But if I already got that tip during the first harvest, and gave Balor 50 ore for it, then when I come around again the dialog is unfinished. After I demand the weed, Balor does acknowledge that this is the second time: "Of course, to sell off to the New Camp again? I wanna see 50 ore, my usual advance payment". However, the dialog ends there. I get no chance to respond, I do not receive weed nor is 50 ore taken.

[Saves.zip](https://github.com/AmProsius/gothic-1-community-patch/files/8009222/Saves.zip)

**Comment by AmProsius** [comment] 2022-02-06 04:56
Duplicate of #267.

**Closed** 2022-02-06 04:57 UTC
Labels: validation: required
