### ISSUE TITLE
Spelling - Improved Ore Armor (EN)

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#150] opened 2021-02-24 23:04 UTC
**Describe the bug**
In the English localization there's a typo in the Improved Ore Armor's name.

**Changelog**
Changed the name "Improved ore Armor" to "Improved Ore Armor".

**Comment by AmProsius** [comment] 2021-02-24 23:04
https://github.com/AmProsius/gothic-1-community-patch/blob/703d7554a7623acd2abbf79318c53dd3ed744690/scriptbase/_work/Data/Scripts/Content/Items/Armor.d#L1127

changed to

```d
name                    =   "Improved Ore Armor";
```

**Comment by szapp** [comment] 2021-03-17 08:53
Duplicate of #149

**Closed** 2021-03-20 21:33 UTC
Labels: fix provided, impl: replace assign/push str, language depended, type: session fix, validation: validated
