### ISSUE TITLE
Scar has no bolts

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#169] opened 2021-03-01 08:40 UTC
**Describe the bug**
Scar owns the most powerful crossbow in the entire game, but he can't use it, because he has no bolts.

**Expected behavior**
Scar now has bolts so he can actually use his crossbow.

**Additional context**
The amount of bolts is `opinionated`, but I suggest giving him the same amount as Jackal (who owns the second most powerful crossbow):
https://github.com/AmProsius/gothic-1-community-patch/blob/0623f55a4ba7811367e2bc52a879724c4616717e/scriptbase/_work/Data/Scripts/Content/Story/NPC/GRD_201_Jackal.d#L39-L42

**Comment by AmProsius** [comment] 2021-03-01 08:43
https://github.com/AmProsius/gothic-1-community-patch/blob/0623f55a4ba7811367e2bc52a879724c4616717e/scriptbase/_work/Data/Scripts/Content/Story/NPC/EBR_101_Scar.d#L45

changed to 

```d
    CreateInvItem(self, ItRw_Crossbow_04);
    CreateInvItems(self, ItAmBolt, 15);
```

**Comment by szapp** [comment] 2021-03-01 08:57
Is the ammunition not auto-generated when the NPC is updated/placed into the world? I think I vaguely remember something like that from working on GFA (see [here](https://github.com/szapp/GothicFreeAim/blob/3302ac3ad6e9c83245392a3e11cd67be37802cce/_work/data/Scripts/Content/GFA/_intern/init.d#L255-L259)). However, I don't remember under which conditions that takes effect. We should validate if Scar in fact doesn't have any bolts by going to him and checking his inventory in the running game.

**Comment by AmProsius** [comment] 2021-03-01 09:05
> We should validate if Scar in fact doesn't have any bolts by going to him and checking his inventory in the running game.

I will write that on my to do list.

**Comment by AmProsius** [comment] 2021-03-05 20:57
Scar definitely has no bolts and the crossbow isn't even equipped. I updated the fix accordingly.

![ScreenShot_2021_3_5_21_52_12](https://user-images.githubusercontent.com/2817152/110172565-9bdbc000-7dfd-11eb-8eb9-ef1276898b2d.jpg)

**Comment by szapp** [comment] 2021-03-13 21:37
Does this also happen without the G1CP (in the vanilla game)? Because typically the best weapons should be auto-equipped. If that is not the case here, I suspect #59 might be interfering (although I wouldn't know how).

**Comment by szapp** [comment] 2021-03-13 22:19
I now understand the circumstances. Here a short explanation and a list of how to reproduce it.

There are two functions in the engine:

1. If an NPC has a ranged weapon and could equip it, but has no matching ammunition, 50 items of the ammunition are auto-generated. This event is triggered only during level changes or when it is midnight (*not* triggered when sleeping).
2. If an NPC has a ranged weapon and could equip it and has enough ammunition, it is equipped. This event is triggered when the NPC is "enabled" - that means if the player comes into range. (This is btw what #59 intercepts to skip if a weapon of the type is already equipped.)

What that means: Since it is highly unlikely that the player will manage to reach Scar before any level change and/or hitting midnight, I do not think we need to treat this as an issue. At some point the player will change the world and from that point on Scar will have his crossbow equipped.

Steps to verify:
- Start new game
- Console: `goto waypoint OCC_CORNER_1`
- Use `k` to jump through the wall on the left
- Confirm that Scar does not have his crossbow equipped (if desired check that he has no bolts)
- Console: `set time 23 59`
- Wait a few seconds
- If desired check if he has bolts now
- Console: `goto waypoint START`
- Console: `goto waypoint OCC_CORNER_1`
- Confirm that he now has his crossbow equipped

I think we can close this issue.

**Closed** 2021-03-13 22:32 UTC
